from dataclasses import dataclass

from apps.next_period_high_low.trainer.base import NextPeriodHighLowTrainerService

@dataclass
class NextPeriodHighLowPriceTrainerService(NextPeriodHighLowTrainerService):
	pass